### ISSUE TITLE
cannot run test with mocha

### ISSUE THREAD

**Issue by FredericHeem** [stellar/js-stellar-base#30]
At the moment, mocha cannot run the tests out of the box because tests are written in es6.
Here is the fix: https://github.com/FredericHeem/js-stellar-base/commit/87d8f525c0fedbf090764a507c513dfe552b67ae

**Comment by bartekn** [comment]
Please use: `gulp test:node`

**Comment by FredericHeem** [comment]
How do you run one specific test ?
With mocha, the -g  option is used.
What prevents you to inclue this change that is already written ?

**Comment by bartekn** [comment]
Simply adding `--require babel/register` in mocha.opts won't solve the problem. To solve it we would need to rewrite setup files in a way that all necessary objects and functions are loaded. We definitely won't be able to make all these changes before new network launch.

I suggested `gulp test:node` because right now it takes around 3 seconds to run all tests so it's quite handy.

I will be happy to merge your PR solving this but it needs to work.

**Comment by bartekn** [comment]
Closed in https://github.com/stellar/js-stellar-base/commit/2f5e99352a04aa60fc6cb8234456b3f40806aa11
