### ISSUE TITLE
Rename createSubaccount to createMuxedAccount

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/js-stellar-base#433]
The Account class has a function, `createSubaccount`.

I propose we rename it, safely with deprecation, etc, to `createMuxedAccount`.

The function name `createSubaccount` makes assumptions about how muxed accounts will be used. Muxed accounts are intended to solve a variety of problems, and only one of them is the ability to represents virtual accounts. They're also intended to support invoicing and really any memo transaction case where the receiver or sender wish to track a specific transaction.

**Comment by Shaptic** [comment]
This was done in an effort to better-describe the meaning / purpose of a muxed account, but you're right in that it describes a too-specific use case. I support a rename (and will keep this issue in mind for the next major version bump); I just wish we had a better one. Multiplexing is such a deeply-technical term...

**Comment by Shaptic** [comment]
In #485, I propose removing `Account.createSubAccount(id)` and introducing `MuxedAccount.createSibling(id)`.

The reason is that if you'd like to create a muxed account and you have an `Account`, you should just use `new MuxedAccount()`. If you just want to create an `M...` address, you should use `encodeMuxedAccount(gAddress, id)`. The only scenario in which a "create related muxed account" helper makes sense is when you already have a `MuxedAccount` instance.

**Comment by leighmcculloch** [comment]
I think we could drop `createSubAccount` and rely on this existing behavior:

```js
MuxedAccount.fromAddress(account.accountId(), id);
```

`createSibling` would introduce a new concept that is probably unnecessary given that you could just do the above instead, which is still a short single line.

@Shaptic Wdyt?

**Comment by leighmcculloch** [comment]
Ah yes, I misread the docs.

Are you asking if we should keep createSubaccount? I don't feel strongly. If we keep it I think we should name it `createMuxedAccount()` because that is what it is creating. Sibling introduces a new concept to learn.

I also think it would be fine to remove `createSubaccount` and require folks to do the following, which is fine:

```js
const mux3 = new StellarBase.MuxedAccount(mux2.baseAccount(), '3'); 
```

Something that occurs to me:

Is there a way to create an M address from a G+id without a sequence number?

It is the most confusing thing to me in all of this is that MuxedAccount and Account have sequence numbers. I realize this is a common thing in all the Stellar SDKs.

**Comment by Shaptic** [comment]
> If we keep it I think we should name it createMuxedAccount() because that is what it is creating. Sibling introduces a new concept to learn.

Right, but this isn't _just_ a muxed account: the underlying base account is shared, and this has important implications re: sequence number. Hence the `sibling` naming. I think the best plan is just to drop it, because this concept is much more explicit in the snippet you shared above (since they must call `.baseAccount()`).

> Is there a way to create an M address from a G+id without a sequence number?

Yes, it's done via `encodeMuxedAccount(gAddress: string, id: string): string`

> It is the most confusing thing to me in all of this is that MuxedAccount and Account have sequence numbers.

I agree, but it's necessary so that you can pass `MuxedAccount`s to `TransactionBuilder`s and get both the M-address and sequence number get updated.
