### ISSUE TITLE
Move `Account. isValidAccountId`

### ISSUE THREAD

**Issue by bartekn** [stellar/js-stellar-base#62]
`Keypair` class seems to be a better place.

**Comment by irisli** [comment]
I agree and just naming it as isValidPublicKey. And then adding a isValidSecretKey would be handy too.

Would it be a good idea to have Account.isValidAccountId for convenience?

**Comment by johansten** [comment]
There's already been some changes done, in regards to 'address'-> 'accountId'. But.. all accountId's are addresses, whereas the oppositse just isn't true..

So 'address' or maybe ¨publickey' is the more appropriate.

E.g., isValidAccountId shouldn't return true unless the address/public key corresponds to an account registered in the ledger. If it's not in the ledger it's always invalid, no matter if the base32-string is a valid address or not.

**Comment by jedmccaleb** [comment]
What are you meaning when you say "address"? We are defining "address" as things like `bob*kraken.com`
If you want to look up in the ledger to see if a particular accountID exists or not that is what loadAccount does

**Comment by johansten** [comment]
OK.. Then it's either a public key or an account Id.

Since it's only an account if it's in the ledger, isValidAccountID ought to check the ledger to see if the provided publickey is registered as an account. Otherwise the function should be called isValidPublicKey, as per Iris' comment.

(Cache invalidation and naming things, eh)
